#!/usr/bin/env python3
"""Generate agentkit/rules.index.md: every ##/### section with its line range."""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent  # agentkit/
RULES = ROOT / "RULES.md"
OUT = ROOT / "rules.index.md"


def build() -> str:
    lines = RULES.read_text(encoding="utf-8").splitlines()
    heads = [(i + 1, m.group(1), m.group(2).strip())
             for i, ln in enumerate(lines)
             if (m := re.match(r"^(#{1,3})\s+(.*)$", ln))]
    out = [
        "# RULES.md index",
        "",
        "<!-- generated by tools/rules_index.py; do not edit -->",
        "",
        "Read the section you need by its line range; never read the whole file (199 KB).",
        "",
        "| lines | heading |",
        "|---|---|",
    ]
    for i, (start, level, title) in enumerate(heads):
        end = heads[i + 1][0] - 1 if i + 1 < len(heads) else len(lines)
        out.append(f"| {start}–{end} | {'#' * len(level)} {title} |")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> None:
    text = build()
    if "--check" in argv:
        raise SystemExit(0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else 1)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main(sys.argv[1:])
